### PR TITLE
Add KeyboardScrollView subclass

### PR DESCRIPTION
**Pull request by peuf0u**

### CODE REVIEW

**Comment by mkj-is** [comment]
There are conflicts with the project file, which was removed.

Do you think we should keep two ways of handling keyboard? Now we have the constraint and this solution and they are very similar to each other. At least we can reuse some of the code, can't we?

**Review by mkj-is — CHANGES_REQUESTED** [review]
Reasons left in the comment to the whole pull request.

**Comment by peuf0u** [comment]
> There are conflicts with the project file, which was removed.
> 
> Do you think we should keep two ways of handling keyboard? Now we have the constraint and this solution and they are very similar to each other. At least we can reuse some of the code, can't we?

I think we should keep them both. Because `KeyboardConstraint` is still useful when it comes to pined bottom button or when your layout does not contain UIScrollView and yes a I think we can reuse some of the code. I will have a look on this. Thanks

**Comment by peuf0u** [comment]
@mkj-is I've tried to reuse some of the common code with `KeyboardConstraint` but there is just one method that's identical and in my opinion it won't be any useful to isolate it.

**Review by mkj-is — APPROVED** [review]
Seems legit.

One thing I still think could be improved is documentation:

- Add both ways to handle keyboard to README with some guidance on when to use them.
- Add some inline documentation to the `class`

**Comment by mkj-is** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
